### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'targetNamespace' of null

### ISSUE THREAD

**Issue by tonibache** [sevenclev/node-soap-graphql#1]
I have tried to use your library with this wsdl, but it always failed.
Can you have a look ? Thks
[OXResellerContextService.txt](https://github.com/sevenclev/node-soap-graphql/files/2888737/OXResellerContextService.txt)

**Comment by saerdnaer** [comment]
you can also try this fork, which fixes that problem with: https://github.com/sevenclev/node-soap-graphql/commit/51cb337d3ac38b48399ca2b2ba0de5ff67a6e02e
